### ISSUE TITLE
Unable to get bluebrain/bioexplorer docker container running.

### ISSUE THREAD

**Issue by ItzDerock** [BlueBrain/BioExplorer#130]
Exits with `Failed to connect to database, check command line parameters. could not translate host name "port=" to address: Name or service not known`

Is there some documentation on setting up a database?

**Comment by favreau** [comment]
Thanks for reporting this. There is a description of the DB schemas there: https://github.com/BlueBrain/BioExplorer/tree/master/storage/database.
We currently use a PostgreSQL database but I agree the documentation and on sample datasets are clearly missing. I am on it but this will take a little while.
In the meantime, I made the DB connection optional. This should still make all molecular use-cases available (https://github.com/BlueBrain/BioExplorer/pull/132)
