### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [BlueBrain/BioExplorer#179]
💭 Would you like to [wrap any pointers](https://github.com/BlueBrain/BioExplorer/blob/5aa3b30a3e511f5d70dda4de1833ab1d9b23a8e9/bioexplorer/core/plugin/io/CacheLoader.cpp#L436 "Update candidate: CacheLoader::_readString()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by favreau** [comment]
Fixed by https://github.com/BlueBrain/BioExplorer/pull/236

**Comment by elfring** [comment]
Thanks for your small source code adjustment.
